### ISSUE TITLE
ESE Line 976

### ISSUE THREAD

**Issue by ml0130** [ewhitaker-zhu/ZHU-Euroscope#8]
@ewhitaker-zhu reference that I know why its throwing that but it shouldn't be
![image](https://user-images.githubusercontent.com/27445711/120052509-86c89480-bfda-11eb-9314-afc0a972ac88.png)

**Comment by ewhitaker-zhu** [comment]
Solved. There were spaces between coordinate Lat/Long, whereas it should be XXX:WXX.  But for now, let's keep the issue open in case any other COORD errors appear.

**Comment by ewhitaker-zhu** [comment]
Actually, if it isn't appearing anymore, I'll close the issue.
